name         'adcade-thrift'
version      '0.1.1'
summary      'Download, compile and install thrift'
description  'Download, compile and install thrift'
author       'Yangming Huang, Kris J. Pruden'
license      'MIT'
project_page 'https://github.com/Adcade/puppet-thrift'
dependency   'puppetlabs/nodejs',  '>=0.2.1'
dependency   'puppetlabs/vcsrepo', '>=0.2.0'
dependency   'BenoitCattie/nginx', '>=0.0.2'
dependency   'ideas/uwsgi',        '>=1.0.0'
