name         'adcade-statsd'
version      '0.2.1'
summary      'Install statsd and graphite'
description  'Install statsd and graphite'
author       'Yangming Huang'
license      'MIT'
project_page 'https://github.com/Adcade/puppet-statsd'
dependency   'puppetlabs/nodejs',  '>=0.2.1'
dependency   'puppetlabs/vcsrepo', '>=0.2.0'
dependency   'BenoitCattie/nginx', '>=0.0.2'
dependency   'adcade/uwsgi',       '>=1.0.0'
